name: "Arcane Control"
description: "Control HA from a fricking Wii or Windows Phone"
version: "0.3.4"
slug: "arcane_control"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  944/tcp: 944
options:
  buttons:
    - text: null
      service: null
      service_data: null
schema:
  buttons:
    - text: str
      service: str
      service_data: str?
